### ISSUE TITLE
Issuer Key Rotation in the Event of compromised Issuer private key.

### ISSUE THREAD

**Issue by SmithSamuelM** [hyperledger/anoncreds-spec#119]
The Indy AnonCreds Design here [Anoncreds Design](https://github.com/hyperledger/indy-node/blob/main/design/anoncreds.md) included provisions for key rotation leveraging the Indy/Sovrin Ledger.  I see no mention of key rotation in this specification. How do you plan on providing for key rotation in the event the private key of the Issuer becomes compromised?

**Comment by swcurran** [comment]
Currently, the only method I'm aware of in AnonCreds for dealing with a Cred Def (which is the object that contains the public keys for a issuing a credential) is to create a new one, stop using the old one when issuing and only issue with the new Cred Def.  Any existing credentials issued with the old Cred Def would reference the old Cred Def, any new credentials, the old Cred Def.

In theory, an issuer could do more.  An Issuer with an Aries agent that retains a persistent DIDComm connection to the holders, would have a way to proactively issue a new credential to replace all of the old ones. If revocation is active for the credential type, the issuer could revoke all of the credentials associated with the old Cred Def.

**Comment by SmithSamuelM** [comment]
So if the the private key of the public keys is compromised what stops the compromiser from issuing fraudulent credentials under the old cred def? How does a verifier know that credentials should be using the new cred def not that old one. The Indy AnonCreds design used time-stamps of the key state on the ledger for the cred defs to signal that old public keys in the cred defs were no longer valid and a verifier had to check the time stamp provided by a majority BLS sig of the ledger nodes.
Simply issuing a new cred def doesn't invadate credentials issued under the old cred def, unless the policty is to auto-revoke all credentials issued under the old cred def the instant the new cred def is published.

How does the legitimate issuer know that their key has been compromised and that they need to issue a new cred def. Given that the purpose of using Anoncreds is to prevent issuer linkability at presentation, a verifier would have to volunteer to the Issuer that they suspected an fraudulent issuance in spite of it being verifiable.

Seems heavy weight to require a persistent didcom connection from issuers to holders. Not to mention that survelliance privacy issues such a persistent connection would engender for third party survellors.

Without a normative key rotation mechanism, key compromise makes anoncreds fundamentally insecure.

**Comment by SmithSamuelM** [comment]
All that said. AnonCreds may choose not to have a normative key rotation mechanism, but then the spec should be caveated that it should/must be used with some key rotation mechanism and some though should go into providing normative hooks in AnonCreds for such mechanisms.

**Comment by swcurran** [comment]
Is this part of the "all roads must lead to KERI?" tour, Sam?

I've quoted a few of your questions and responded as per the AnonCreds model.

> So if the the private key of the public keys is compromised what stops the compromiser from issuing fraudulent credentials under the old cred def?
  * Assuming the malicious actor replicates the environment of the Issuer and can attract holders interested in receiving a credential from the malicious actor, nothing stops them. It depends on how much control/information they have over the Issuer as to how effective it would be.
> How does a verifier know that credentials should be using the new cred def not that old one?
  * Either the verifier does not know to ask for credentials from the new CredDef (and so never gets them -- holder can't satisfy the presentation request with the new credential) or the verifier gets a presentation that uses the new credential, with the Id of the new CredDef and they must decide if they trust it or not. As such, your definition of "how Indy did it" remains the same.
> Simply issuing a new cred def...
* Correct. And as noted, revocation is an option if the credential type supports revocation. Batch revocation is possible, although there is not "automation tied to publishing the new cred def", unless the issuer implements that. That is a policy issue supported by, but well above AnonCreds.
> How does the legitimate issuer know that their key has been compromised and that they need to issue a new cred def? 
* There is no specified way to handle this as by definition. it is unknown. The issuer might detect the compromise. Verifiers could contact the Issuer (perhaps using the IssuerId in the credential) or perhaps a Trust Registry that supports reporting abuse could be used.  This issue is well-above the AnonCreds protocol and part of governance.
> Seems heavy weight to require a persistent didcom connection from issuers to holders. Not to mention that survelliance/privacy issues such a persistent connection would engender third party surveillors to correlate holders to the credentials they hold...
* There is no requirement to have a DIDComm connection. An issuer unilaterally revokes credentials -- the DIDComm connection can help them with notifications of the revocation and optionally, re-issuance. I merely offered that as a policy that an issuer might want to use, a deployment model they might choose. There is no surveillance about keeping a persistent connection.  An issuer supporting revocation MUST track the holder and credential issued in order to revoke the credential.  Again, no surveillance, just a technical requirement.

Rest of your response are statements.

There is a security section in the specification and in that, we'll include the issue of compromised keys and the options an issuer has, mostly outlined in this issue.

Thank you for raising this issue.

**Comment by SmithSamuelM** [comment]
Very much appreciate your thoughtful responses.

> Is this part of the "all roads must lead to KERI?" tour, Sam?

Actually i was trying to see what it would take to use AnonCreds as an optional proof type for ACDCs and ran into the inherent trade-off between stronger authenticiy and weaker privacy or weaker authenticity and stronger privacy that is a fundamental property of the limited crypto options at our disposal.  I raised this issue primarly becasue  I wanted see this new spec for AnonCreds sans Indy had any new thinking on the key rotation problem. 

We have a very limited set of properties we can play with and as expressed by the PAC theorem we have a trilemma when doing systems design. We can have all of Privacy, Authenticity, and Confidentiality at some level of security but not all three at the highest level. We must pick two. Usually the trade is between Authenticity and Privacy and key rotation is one of the sticky points that forces the trade. PKI can only do so much and ZKPs can only do so much and when you want absoulte unlinkability you must give up some other property to some degree.

KERI is opinionated in that it makes the choice to always have authenticity as the strongest of the three which necessarily means some compromise on privacy. It may not be a big compromise but the one that is sticky point is malicious unpermissioned correlation between Issuer and Issuee by a verifier. All the other correlations can be dealt with without sacrificing authenticity. It is the trade-off induced by key rotation vis a vis linking key state to revocation state that is the problem. 

I have yet to see a satisfying approach to key rotation that doesn't make a trade-off between linkability and authenticity (secure attribution).

**Comment by rodolfomiranda** [comment]
Interesting discussion! Is that something we can tag as `next version`?

**Comment by swcurran** [comment]
Closing this issue.  The “solution” for key rotation is “cred def rotation” — a new cred def is used.
